// DO NOT EDIT: generated by TupleEncodingSpec.scala
package scommons.websql.encoding

trait TupleEncoders extends BaseEncodingDsl {

  implicit def tuple2Encoder[T1, T2](
    implicit e1: Encoder[T1], e2: Encoder[T2]
  ): Encoder[(T1, T2)] =
    WebSqlEncoder { (_: Index, v: (T1, T2), row: PrepareRow) =>
      e2(-1, v._2,
        e1(-1, v._1, row))
    }

  implicit def tuple3Encoder[T1, T2, T3](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3]
  ): Encoder[(T1, T2, T3)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3), row: PrepareRow) =>
      e3(-1, v._3,
        e2(-1, v._2,
          e1(-1, v._1, row)))
    }

  implicit def tuple4Encoder[T1, T2, T3, T4](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4]
  ): Encoder[(T1, T2, T3, T4)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4), row: PrepareRow) =>
      e4(-1, v._4,
        e3(-1, v._3,
          e2(-1, v._2,
            e1(-1, v._1, row))))
    }

  implicit def tuple5Encoder[T1, T2, T3, T4, T5](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5]
  ): Encoder[(T1, T2, T3, T4, T5)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5), row: PrepareRow) =>
      e5(-1, v._5,
        e4(-1, v._4,
          e3(-1, v._3,
            e2(-1, v._2,
              e1(-1, v._1, row)))))
    }

  implicit def tuple6Encoder[T1, T2, T3, T4, T5, T6](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6]
  ): Encoder[(T1, T2, T3, T4, T5, T6)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6), row: PrepareRow) =>
      e6(-1, v._6,
        e5(-1, v._5,
          e4(-1, v._4,
            e3(-1, v._3,
              e2(-1, v._2,
                e1(-1, v._1, row))))))
    }

  implicit def tuple7Encoder[T1, T2, T3, T4, T5, T6, T7](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7), row: PrepareRow) =>
      e7(-1, v._7,
        e6(-1, v._6,
          e5(-1, v._5,
            e4(-1, v._4,
              e3(-1, v._3,
                e2(-1, v._2,
                  e1(-1, v._1, row)))))))
    }

  implicit def tuple8Encoder[T1, T2, T3, T4, T5, T6, T7, T8](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8), row: PrepareRow) =>
      e8(-1, v._8,
        e7(-1, v._7,
          e6(-1, v._6,
            e5(-1, v._5,
              e4(-1, v._4,
                e3(-1, v._3,
                  e2(-1, v._2,
                    e1(-1, v._1, row))))))))
    }

  implicit def tuple9Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9), row: PrepareRow) =>
      e9(-1, v._9,
        e8(-1, v._8,
          e7(-1, v._7,
            e6(-1, v._6,
              e5(-1, v._5,
                e4(-1, v._4,
                  e3(-1, v._3,
                    e2(-1, v._2,
                      e1(-1, v._1, row)))))))))
    }

  implicit def tuple10Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10), row: PrepareRow) =>
      e10(-1, v._10,
        e9(-1, v._9,
          e8(-1, v._8,
            e7(-1, v._7,
              e6(-1, v._6,
                e5(-1, v._5,
                  e4(-1, v._4,
                    e3(-1, v._3,
                      e2(-1, v._2,
                        e1(-1, v._1, row))))))))))
    }

  implicit def tuple11Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11), row: PrepareRow) =>
      e11(-1, v._11,
        e10(-1, v._10,
          e9(-1, v._9,
            e8(-1, v._8,
              e7(-1, v._7,
                e6(-1, v._6,
                  e5(-1, v._5,
                    e4(-1, v._4,
                      e3(-1, v._3,
                        e2(-1, v._2,
                          e1(-1, v._1, row)))))))))))
    }

  implicit def tuple12Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12), row: PrepareRow) =>
      e12(-1, v._12,
        e11(-1, v._11,
          e10(-1, v._10,
            e9(-1, v._9,
              e8(-1, v._8,
                e7(-1, v._7,
                  e6(-1, v._6,
                    e5(-1, v._5,
                      e4(-1, v._4,
                        e3(-1, v._3,
                          e2(-1, v._2,
                            e1(-1, v._1, row))))))))))))
    }

  implicit def tuple13Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13), row: PrepareRow) =>
      e13(-1, v._13,
        e12(-1, v._12,
          e11(-1, v._11,
            e10(-1, v._10,
              e9(-1, v._9,
                e8(-1, v._8,
                  e7(-1, v._7,
                    e6(-1, v._6,
                      e5(-1, v._5,
                        e4(-1, v._4,
                          e3(-1, v._3,
                            e2(-1, v._2,
                              e1(-1, v._1, row)))))))))))))
    }

  implicit def tuple14Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14), row: PrepareRow) =>
      e14(-1, v._14,
        e13(-1, v._13,
          e12(-1, v._12,
            e11(-1, v._11,
              e10(-1, v._10,
                e9(-1, v._9,
                  e8(-1, v._8,
                    e7(-1, v._7,
                      e6(-1, v._6,
                        e5(-1, v._5,
                          e4(-1, v._4,
                            e3(-1, v._3,
                              e2(-1, v._2,
                                e1(-1, v._1, row))))))))))))))
    }

  implicit def tuple15Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15), row: PrepareRow) =>
      e15(-1, v._15,
        e14(-1, v._14,
          e13(-1, v._13,
            e12(-1, v._12,
              e11(-1, v._11,
                e10(-1, v._10,
                  e9(-1, v._9,
                    e8(-1, v._8,
                      e7(-1, v._7,
                        e6(-1, v._6,
                          e5(-1, v._5,
                            e4(-1, v._4,
                              e3(-1, v._3,
                                e2(-1, v._2,
                                  e1(-1, v._1, row)))))))))))))))
    }

  implicit def tuple16Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16), row: PrepareRow) =>
      e16(-1, v._16,
        e15(-1, v._15,
          e14(-1, v._14,
            e13(-1, v._13,
              e12(-1, v._12,
                e11(-1, v._11,
                  e10(-1, v._10,
                    e9(-1, v._9,
                      e8(-1, v._8,
                        e7(-1, v._7,
                          e6(-1, v._6,
                            e5(-1, v._5,
                              e4(-1, v._4,
                                e3(-1, v._3,
                                  e2(-1, v._2,
                                    e1(-1, v._1, row))))))))))))))))
    }

  implicit def tuple17Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17), row: PrepareRow) =>
      e17(-1, v._17,
        e16(-1, v._16,
          e15(-1, v._15,
            e14(-1, v._14,
              e13(-1, v._13,
                e12(-1, v._12,
                  e11(-1, v._11,
                    e10(-1, v._10,
                      e9(-1, v._9,
                        e8(-1, v._8,
                          e7(-1, v._7,
                            e6(-1, v._6,
                              e5(-1, v._5,
                                e4(-1, v._4,
                                  e3(-1, v._3,
                                    e2(-1, v._2,
                                      e1(-1, v._1, row)))))))))))))))))
    }

  implicit def tuple18Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17], e18: Encoder[T18]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18), row: PrepareRow) =>
      e18(-1, v._18,
        e17(-1, v._17,
          e16(-1, v._16,
            e15(-1, v._15,
              e14(-1, v._14,
                e13(-1, v._13,
                  e12(-1, v._12,
                    e11(-1, v._11,
                      e10(-1, v._10,
                        e9(-1, v._9,
                          e8(-1, v._8,
                            e7(-1, v._7,
                              e6(-1, v._6,
                                e5(-1, v._5,
                                  e4(-1, v._4,
                                    e3(-1, v._3,
                                      e2(-1, v._2,
                                        e1(-1, v._1, row))))))))))))))))))
    }

  implicit def tuple19Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17], e18: Encoder[T18], e19: Encoder[T19]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19), row: PrepareRow) =>
      e19(-1, v._19,
        e18(-1, v._18,
          e17(-1, v._17,
            e16(-1, v._16,
              e15(-1, v._15,
                e14(-1, v._14,
                  e13(-1, v._13,
                    e12(-1, v._12,
                      e11(-1, v._11,
                        e10(-1, v._10,
                          e9(-1, v._9,
                            e8(-1, v._8,
                              e7(-1, v._7,
                                e6(-1, v._6,
                                  e5(-1, v._5,
                                    e4(-1, v._4,
                                      e3(-1, v._3,
                                        e2(-1, v._2,
                                          e1(-1, v._1, row)))))))))))))))))))
    }

  implicit def tuple20Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17], e18: Encoder[T18], e19: Encoder[T19], e20: Encoder[T20]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20), row: PrepareRow) =>
      e20(-1, v._20,
        e19(-1, v._19,
          e18(-1, v._18,
            e17(-1, v._17,
              e16(-1, v._16,
                e15(-1, v._15,
                  e14(-1, v._14,
                    e13(-1, v._13,
                      e12(-1, v._12,
                        e11(-1, v._11,
                          e10(-1, v._10,
                            e9(-1, v._9,
                              e8(-1, v._8,
                                e7(-1, v._7,
                                  e6(-1, v._6,
                                    e5(-1, v._5,
                                      e4(-1, v._4,
                                        e3(-1, v._3,
                                          e2(-1, v._2,
                                            e1(-1, v._1, row))))))))))))))))))))
    }

  implicit def tuple21Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17], e18: Encoder[T18], e19: Encoder[T19], e20: Encoder[T20], e21: Encoder[T21]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21), row: PrepareRow) =>
      e21(-1, v._21,
        e20(-1, v._20,
          e19(-1, v._19,
            e18(-1, v._18,
              e17(-1, v._17,
                e16(-1, v._16,
                  e15(-1, v._15,
                    e14(-1, v._14,
                      e13(-1, v._13,
                        e12(-1, v._12,
                          e11(-1, v._11,
                            e10(-1, v._10,
                              e9(-1, v._9,
                                e8(-1, v._8,
                                  e7(-1, v._7,
                                    e6(-1, v._6,
                                      e5(-1, v._5,
                                        e4(-1, v._4,
                                          e3(-1, v._3,
                                            e2(-1, v._2,
                                              e1(-1, v._1, row)))))))))))))))))))))
    }

  implicit def tuple22Encoder[T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22](
    implicit e1: Encoder[T1], e2: Encoder[T2], e3: Encoder[T3], e4: Encoder[T4], e5: Encoder[T5], e6: Encoder[T6], e7: Encoder[T7], e8: Encoder[T8], e9: Encoder[T9], e10: Encoder[T10], e11: Encoder[T11], e12: Encoder[T12], e13: Encoder[T13], e14: Encoder[T14], e15: Encoder[T15], e16: Encoder[T16], e17: Encoder[T17], e18: Encoder[T18], e19: Encoder[T19], e20: Encoder[T20], e21: Encoder[T21], e22: Encoder[T22]
  ): Encoder[(T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22)] =
    WebSqlEncoder { (_: Index, v: (T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21, T22), row: PrepareRow) =>
      e22(-1, v._22,
        e21(-1, v._21,
          e20(-1, v._20,
            e19(-1, v._19,
              e18(-1, v._18,
                e17(-1, v._17,
                  e16(-1, v._16,
                    e15(-1, v._15,
                      e14(-1, v._14,
                        e13(-1, v._13,
                          e12(-1, v._12,
                            e11(-1, v._11,
                              e10(-1, v._10,
                                e9(-1, v._9,
                                  e8(-1, v._8,
                                    e7(-1, v._7,
                                      e6(-1, v._6,
                                        e5(-1, v._5,
                                          e4(-1, v._4,
                                            e3(-1, v._3,
                                              e2(-1, v._2,
                                                e1(-1, v._1, row))))))))))))))))))))))
    }

}
